Add factory reset
openconfig/gnoigo pull request #15
Opened 2023-10-20 22:01 UTC by prinikasn

2023-10-21 00:35 UTC, greg-dennis approved these changes

2023-10-23 16:22 UTC, greg-dennis requested changes
Please fix the build failure

2023-10-23 20:29 UTC, prinikasn commented
> Please fix the build failure

For this PR I will remove `RetainCerts` field. I will create another PR to add this and merge once a new gnoi release is available.

2023-10-23 20:34 UTC, greg-dennis approved these changes

2023-10-23 20:35 UTC, merged