Add OS Activate and OS Verify Operations
openconfig/gnoigo pull request #24
Opened 2024-02-16 11:00 UTC by asafsonnv

2024-02-16 18:03 UTC, greg-dennis requested changes
Thanks!

2024-02-16 18:03 UTC, greg-dennis commented on os/os.go
> +// ActivateOperation represents the parameters of a Activate operation.
Can you move this above InstallOperation so we keep the operations alphabetized?

2024-02-26 16:37 UTC, greg-dennis commented
Sorry for the delay. I was away on vacation last week. Can you just add a few single unit tests to os_test.go? These are simple, unary operations, so they would look like TestTime: https://github.com/openconfig/gnoigo/blob/main/system/system_test.go#L312

2024-03-18 10:39 UTC, closed without merging

2024-03-18 10:43 UTC, asafsonnv commented
Hi sorry I accidentally did force push. can we revert it? or should I create a new MR with all the changes?